---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: virtualbox_ubuntu-14.04_chef-12.4.1_1.0.7
      box_url: http://vagrantboxes.hq.daptiv.com/vagrant/boxes/virtualbox_ubuntu-14.04_chef-12.4.1_1.0.7.box
  - name: windows2012r2
    driver:
      box: virtualbox_windows-2012r2_chef-12.5.1_1.0.23
      box_url: http://artrepo.daptiv.com:8081/artifactory/vagrant-local/virtualbox_windows-2012r2_chef-12.5.1_1.0.23.box
    driver_config:
      communicator: winrm
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[google-chrome::default]
