---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04-virtualbox
    driver:
      box_url: <%= ENV['UBUNTU_BOX_URL'] %>
  - name: windows2012r2_chef12
    driver:
      box_url: <%= ENV['WINDOWS_BOX_URL'] %>
    driver_config:
      communicator: winrm
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[google-chrome::default]
